// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVO4S_qv0vYktRdbqUt6Qv0mrWbFlCBfE',
    appId: '1:658833652462:web:75fd2cc1885c3da25951ff',
    messagingSenderId: '658833652462',
    projectId: 'nexusai-2eb75',
    authDomain: 'nexusai-2eb75.firebaseapp.com',
    storageBucket: 'nexusai-2eb75.firebasestorage.app',
    measurementId: 'G-D4RVDJMMHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuWIOPNM3V_MEjCMGUz6MSx_MRKr3FKrA',
    appId: '1:658833652462:android:178a99a91fb74ef55951ff',
    messagingSenderId: '658833652462',
    projectId: 'nexusai-2eb75',
    storageBucket: 'nexusai-2eb75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKc1A4N0mp6gNWEbWRq3eXopZg2F7vsXg',
    appId: '1:658833652462:ios:a72b3427b7cf29e45951ff',
    messagingSenderId: '658833652462',
    projectId: 'nexusai-2eb75',
    storageBucket: 'nexusai-2eb75.firebasestorage.app',
    iosBundleId: 'com.example.nexusAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKc1A4N0mp6gNWEbWRq3eXopZg2F7vsXg',
    appId: '1:658833652462:ios:a72b3427b7cf29e45951ff',
    messagingSenderId: '658833652462',
    projectId: 'nexusai-2eb75',
    storageBucket: 'nexusai-2eb75.firebasestorage.app',
    iosBundleId: 'com.example.nexusAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVO4S_qv0vYktRdbqUt6Qv0mrWbFlCBfE',
    appId: '1:658833652462:web:d5ff3650cc1f5f285951ff',
    messagingSenderId: '658833652462',
    projectId: 'nexusai-2eb75',
    authDomain: 'nexusai-2eb75.firebaseapp.com',
    storageBucket: 'nexusai-2eb75.firebasestorage.app',
    measurementId: 'G-EQW8NZBW4V',
  );
}
